services:
  ignition:
    healthcheck:
      disable: true
    labels:
      traefik.enable: "true"
      traefik.http.routers.neo4j-ignition.entrypoints: "web"
      traefik.http.routers.neo4j-ignition.rule: "Host(`neo4j-ignition.localtest.me`)"
      traefik.http.services.neo4j-ignition.loadbalancer.server.port: "8088"
    environment:
      GATEWAY_SYSTEM_NAME: neo4j-ignition
      GATEWAY_PUBLIC_HTTP_PORT: 80
      GATEWAY_PUBLIC_HTTPS_PORT: 443
      GATEWAY_PUBLIC_ADDRESS: neo4j-ignition.localtest.me
    networks:
      - default
      - proxy

  neo4j:
    labels:
        traefik.enable: "true"
        traefik.http.routers.neo4j-db.entrypoints: "web"
        traefik.http.routers.neo4j-db.rule: "Host(`neo4j-db.localtest.me`)"
        traefik.http.services.neo4j-db.loadbalancer.server.port: "7474"
    networks:
      - default
      - proxy

networks:
  default:
  proxy:
    external: true
    name: proxy