name: Build Module

on:
  release:
    types: [published]
  
  workflow_dispatch:

jobs:
  assembleRelease: 
    name: restoreReleaseKeystore
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > release.keystore.asc
          gpg -d --passphrase "${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}" --batch release.keystore.asc > release.keystore
          cat "${{ secrets.CERT_FILE_TEXT }}" > cert.crt
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: assembleRelease
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: ./gradlew build --keystoreFile=release.keystore --keystorePassword="${{ secrets.KEYSTORE_PASSWORD }}"  --certFile=cert.crt --certPassword="${{ secrets.CERT_PASSWORD }}" --certAlias="${{ secrets.CERT_ALIAS }}"
  
      - 
        name: Upload to Release Action
        uses: Shopify/upload-to-release@v1.0.1
        with:
          name: Neo4J-Driver.modl
          path: build/Neo4J-Driver.modl
          repo-token: ${{ secrets.GITHUB_TOKEN }}