name: Upload file to latest release

on:
  release:
    types: [published]

  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  upload-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - uses: actions/setup-java@v1
      with:
        java-package: jdk
        java-version: 11
    - 
      name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
    - 
      name: Unpack Keystore and Cert
      run: |
        echo "${{ secrets.RELEASE_KEYSTORE }}" >> release.keystore.asc;
        gpg -d --passphrase "${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}" --batch release.keystore.asc > release.keystore;
        echo "${{ secrets.CERT_FILE_TEXT }}" > cert.crt;
    - 
      name: Build Module
      run: |
        ./gradlew build signModule --keystoreFile=release.keystore --keystorePassword="${{ secrets.KEYSTORE_PASSWORD }}"  --certFile=cert.crt --certPassword="${{ secrets.CERT_PASSWORD }}" --certAlias="${{ secrets.CERT_ALIAS }}"

    - name: Get latest release
      id: latest-release
      run: |
        latest_release_id=$(curl -H "Authorization: token ${{ env.GITHUB_TOKEN }}" --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r '.id')
        echo "::set-env name=LATEST_RELEASE_ID::$latest_release_id"

    - name: Create release asset
      uses: actions/create-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ env.LATEST_RELEASE_ID }}
        asset_path: ./build/Neo4J-Driver.modl
        asset_name: Neo4J-Driver.modl
        asset_label: "Ignition Module"
        asset_content_type: application/octet-stream
